set PSYQ_DIR=C:\psyq
set PATH=%PSYQ_DIR%\bin;%PSYQ_DIR%\cdemu\bin;%PATH%
set PSX_PATH=%PSYQ_DIR%\bin
set LIBRARY_PATH=%PSYQ_DIR%\lib
set C_PLUS_INCLUDE_PATH=%PSYQ_DIR%\include
set C_INCLUDE_PATH=%PSYQ_DIR%\include
set PSYQ_PATH=%PSYQ_DIR%\bin
set COMPILER_PATH=%PSYQ_DIR%\bin
set GO32=DPMISTACK 1000000 
set G032TMP=C:\WINDOWS\TEMP
set TMPDIR=C:\WINDOWS\TEMP

